export const KNEX_OPTIONS = 'KNEX_OPTIONS';
export const KNEX_CONNECTION = 'KNEX_CONNECTION';

export const FILE_TRACKER_KNEX_OPTIONS = 'FILE_TRACKER_KNEX_OPTIONS';
export const FILE_TRACKER_KNEX_CONNECTION = 'FILE_TRACKER_KNEX_CONNECTION';
