import type { IUserWithMetadata } from '@/types/Auth/User.types';

export const users: IUserWithMetadata[] = [
  {
    id: '0575a836-8015-401c-b4c3-7aa74babcfe2',
    givenName: 'Avery',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7;#C68BFC;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '09d60f06-fd8e-4f35-8956-e308d7126559',
    givenName: 'Blake',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF,#75B6FF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '0bfed7be-5d11-43c4-9ce7-cb8ecc90127b',
    givenName: 'Cameron',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0,#DC67CE',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '0dbc9c1d-db8c-4ac3-9fe2-de2d085bf570',
    givenName: 'Dakota',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '0f17f1cc-c1df-4886-ac88-7a62a4e238e2',
    givenName: 'Emerson',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '13cc55be-e887-4ff8-b932-cbe31d26cd9a',
    givenName: 'Finley',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#E56E96,#E05199',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '19e71e32-4f3e-49ec-ab54-40d008abebcb',
    givenName: 'Gray',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: 'Curator',
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '1a6824ae-18fa-496c-af20-ae3ebd2a7d94',
    givenName: 'Harper',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174;#FAD74B;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '1a877866-6221-4ebb-aedf-6cfd09cd06d8',
    givenName: 'Indigo',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '1ab4626e-99f1-4d42-8b1b-97cd55c2364e',
    givenName: 'Jordan',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874;#F39D41;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '1df12cea-a015-4864-91fe-844343fc5985',
    givenName: 'Kai',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: 'Senior Genetic Counsellor',
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '1e88ac04-ee96-4223-90e6-d89d6e4e8df8',
    givenName: 'Logan',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174;#FAD74B;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '2678e807-9aa9-449f-bc23-b276e0060e97',
    givenName: 'Morgan',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: 'Curator',
    avatar: 'colour:#B5DAFF,#75B6FF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '280b4fa6-984f-461f-a250-fd5bfe792af8',
    givenName: 'Nova',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: 'Clinical Cancer Genetics Consultant',
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '286985ee-4c64-4dee-9bd2-67f6b70d22b2',
    givenName: 'Oakley',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0,#DC67CE',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '289bc840-34cc-4a5f-8ad7-fc3e418e67ff',
    givenName: 'Parker',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#43DED3,#27B8AF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '2afecb9c-a6a5-475e-82b4-88d67bc240b1',
    givenName: 'Quinn',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC;#A297F7;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '2b0e4015-2566-4454-a150-da954b260f04',
    givenName: 'Reese',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0,#DC67CE',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '2cc27b4b-41bf-4723-927e-4c97aa831f95',
    givenName: 'Sawyer',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#A3BE8C,#FFFFFF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '2d2de8e8-041b-4d38-b885-de230101ab61',
    givenName: 'Taylor',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '301c38ed-0fef-4d79-be43-cd8f19501e5a',
    givenName: 'Uma',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#43DED3,#27B8AF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '3127679a-f466-4280-abd0-e342e6f03727',
    givenName: 'Val',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0;#DC67CE;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '3b5e367b-97c9-4ffc-84f9-f18cbf4d6184',
    givenName: 'Winter',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '3e9d82c5-7ae7-45a4-ae1d-e21aee06ea4c',
    givenName: 'Xen',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971,#00AB59',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '3f9502da-7aae-4a35-8126-705e12744735',
    givenName: 'Yael',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '443f20f1-e480-4895-847c-dfb35e02b505',
    givenName: 'Zuri',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: 'Senior Genetic Counsellor',
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '473c82b8-c3f5-4d67-8c3a-54111115b71d',
    givenName: 'Arden',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC;#A297F7;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '47f68a3e-b041-457a-9b5f-d7d66360ca8f',
    givenName: 'Bailey',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0;#DC67CE;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '4a50ede0-9396-4d5d-b4fe-bdcac237e641',
    givenName: 'Casey',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '4b075736-c6b9-465a-8667-f6fd45186fdc',
    givenName: 'Drew',
    familyName: 'Ashford',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '4b7c50df-0056-4ae0-a8d5-249be494d6f7',
    givenName: 'Avery',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971,#00AB59',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '4beb7b3e-391f-4ae6-afd7-c41063e08839',
    givenName: 'Blake',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '4dded491-90a2-411e-a5de-61ab3d18d6be',
    givenName: 'Cameron',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971;#00AB59;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '4fdea0c1-23da-4776-9cfa-e0d2b33298ac',
    givenName: 'Dakota',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '504478d4-bd00-42fd-96d5-e452005a4a1e',
    givenName: 'Emerson',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5,#9B51E0',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '56617196-33df-40d6-8526-68a765dbcae1',
    givenName: 'Finley',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971;#00AB59;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '58a546b7-c112-4504-9696-a69f58dfc5fb',
    givenName: 'Gray',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '59ad84ec-3f4b-4fcf-b3e0-262366cbabcc',
    givenName: 'Harper',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF;#75B6FF;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '5a50cb57-a4fb-4022-a7a7-04c6e2e0921a',
    givenName: 'Indigo',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '5af8cfea-1464-4e33-9fe6-7856b38fee0c',
    givenName: 'Jordan',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0;#DC67CE;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '5dc09490-dff0-46f2-a2e6-bba95da69693',
    givenName: 'Kai',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '5e78b8ed-7b01-479a-b6d0-8c961718e736',
    givenName: 'Logan',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5;#9B51E0;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '612cf661-0094-40b8-a1c3-be531ba8f157',
    givenName: 'Morgan',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971,#00AB59',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '674a5228-a66b-41e4-be1c-c43e819fbb10',
    givenName: 'Nova',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '6a946090-dbb7-4034-a677-920ed4b08d82',
    givenName: 'Oakley',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5;#9B51E0;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '6b4a01f6-fc52-4bc6-b1ef-317f8be0a4c4',
    givenName: 'Parker',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5,#9B51E0',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '6b995eca-7691-4119-838e-5dcd2f66b819',
    givenName: 'Quinn',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#E2EAEC,#D6DAD9',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '6cf4b621-f980-4ad8-be15-9788db6b1754',
    givenName: 'Reese',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '6e958b83-09fc-4cae-8a09-fa530b4e0aaa',
    givenName: 'Sawyer',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971;#00AB59;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '705348e3-3d9d-4eac-b4ff-bc1f936cd09e',
    givenName: 'Taylor',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0,#DC67CE',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '7713a0be-036c-490c-8596-570d6743bc57',
    givenName: 'Uma',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#187c19,#187c19,#FFFFFF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '7c0f2da3-69e5-440c-bcfd-efa937db1b98',
    givenName: 'Val',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971,#00AB59',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '7dc34546-9ebf-4d44-b2ac-9cbc32b03773',
    givenName: 'Winter',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#43DED3,#27B8AF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '7e0c3381-56ce-4998-80c8-ffaae82e1341',
    givenName: 'Xen',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5,#9B51E0',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '858f851a-d7a5-41e3-b72e-b01a584e03a8',
    givenName: 'Yael',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: 'Clinical Geneticist',
    avatar: 'colour:#D9B9F7;#C68BFC;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '85f2d29d-3395-421b-b868-3f6d22c94b6e',
    givenName: 'Zuri',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0;#DC67CE;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '866a535d-9b7b-478f-8ab3-7c88d6215bd5',
    givenName: 'Arden',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971,#00AB59',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '89743070-e8b7-4da0-8e54-951464039c43',
    givenName: 'Bailey',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174;#FAD74B;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '8990e543-9379-4c5d-8c13-1f0a8799aef8',
    givenName: 'Casey',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7;#C68BFC;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '8eb3614c-c50c-4622-9e0a-152ed1de60ca',
    givenName: 'Drew',
    familyName: 'Bennett',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '8ebae2d2-94c3-4d3b-8c9d-e2d2675cf051',
    givenName: 'Avery',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5;#9B51E0;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '8f5582b9-3be4-47ea-87d4-4480031d9957',
    givenName: 'Blake',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971,#00AB59',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '8f6919d6-cdba-44c0-99dd-1b480ec0b7cc',
    givenName: 'Cameron',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5;#9B51E0;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '8fe090ec-7af4-4edc-b585-ded63c0fe8d1',
    givenName: 'Dakota',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C1E1C1,#83C383',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '9216fcbb-6fb6-4a33-8b8d-3a8c5435fac8',
    givenName: 'Emerson',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5,#9B51E0',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '92f8b94c-313c-4bca-9d51-3aefb1519662',
    givenName: 'Finley',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971;#00AB59;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '9444bd99-aeef-4a57-a6fe-5b7901e223ae',
    givenName: 'Gray',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '9546a0cb-08f7-4133-9a20-11c9cfe6a3d3',
    givenName: 'Harper',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5,#9B51E0',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '9db9f74f-09fa-4738-8c3a-ab0cf7d9e23f',
    givenName: 'Indigo',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '9def54a2-75e1-4cd2-87ae-e290b7b1325a',
    givenName: 'Jordan',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874;#F39D41;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: '9e13db78-bcd6-400a-8f24-3725b61fb22f',
    givenName: 'Kai',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'a2a716cd-9514-4a9f-863a-34c0b252a5e4',
    givenName: 'Logan',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF;#75B6FF;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'a66b6c61-f6f0-42bf-804e-0285ce45e083',
    givenName: 'Morgan',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'a7656565-6111-4081-8405-6b2cd4807b23',
    givenName: 'Nova',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174;#FAD74B;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'a76cadf1-2de2-4293-b8e7-e5c019149cda',
    givenName: 'Oakley',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'af233cbb-d10f-45c0-9d67-abb4f8fe5eb5',
    givenName: 'Parker',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'af777b56-696b-4de3-8f84-29ea072fa009',
    givenName: 'Quinn',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF;#75B6FF;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'b25da4ec-b7df-4c7f-8ebb-09231fb6589b',
    givenName: 'Reese',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'b38583f5-3124-46ee-bfe4-7276c7b247f4',
    givenName: 'Sawyer',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC;#A297F7;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'b4e3ff2e-581b-4b2c-a239-9f4243bf1cf8',
    givenName: 'Taylor',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5;#9B51E0;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'b57f0ca6-b924-4b3b-807f-54b750df1250',
    givenName: 'Uma',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#43DED3;#27B8AF;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'b5d40c81-ed4d-468f-a3f3-db0c01ce9b76',
    givenName: 'Val',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'b5e5db1b-cbab-4015-a0e4-37589bf68e88',
    givenName: 'Winter',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174;#FAD74B;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'b9f5f447-9968-4918-a8bc-fbd3667dc907',
    givenName: 'Xen',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'bba51b6d-86d7-402a-a547-d98a99c0ff58',
    givenName: 'Yael',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: 'Clinical Cancer Genetics Consultant',
    avatar: 'colour:#B5DAFF,#75B6FF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'be4f98c1-c4b8-41dc-a631-f93ed5b291aa',
    givenName: 'Zuri',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174;#FAD74B;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'bf67234e-1fb5-4d06-b39b-17312f2bf717',
    givenName: 'Arden',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'bf70bf18-fcf4-4116-bbe0-3477a0b1014f',
    givenName: 'Bailey',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#0EC971;#00AB59;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'bfaec848-1cc4-4acf-990c-ff442fa701f9',
    givenName: 'Casey',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'c083e979-60fa-49bc-8c5a-83de7dcd7a4c',
    givenName: 'Drew',
    familyName: 'Calloway',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF,#75B6FF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'c1e0f0ae-2517-442d-a77b-a571ab0386a3',
    givenName: 'Avery',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0,#DC67CE',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'c22a3dba-d2db-4008-84ad-f077001c06f3',
    givenName: 'Blake',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF;#75B6FF;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'c4066421-40c3-41eb-853c-1f74b3b2babc',
    givenName: 'Cameron',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#43DED3,#27B8AF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'c4c210ca-9b7d-4793-a737-121fe4746fe0',
    givenName: 'Dakota',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'cdd32dda-aaef-4f0f-bddf-dbb6f7095c93',
    givenName: 'Emerson',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'd34226ea-0150-48a2-b6c4-5528b5427a51',
    givenName: 'Finley',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874;#F39D41;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'd3eb7d47-3b10-4e0d-bfe9-5ec0e67236d1',
    givenName: 'Gray',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF,#75B6FF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'd483e8dd-7d47-4acb-bd66-cb36ee1c7f95',
    givenName: 'Harper',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF;#75B6FF;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'd5c17f6e-7685-4904-bedf-04b9130be28a',
    givenName: 'Indigo',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'd63b6263-af6f-4203-910b-ca3f6d775b6f',
    givenName: 'Jordan',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#C4BDFC,#A297F7',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'dd68bace-026f-4d6b-95e0-6f5d173f9f57',
    givenName: 'Kai',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#ED7BE0,#DC67CE',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'dee5dbdd-1f55-4dc3-9b6b-25f5f075689f',
    givenName: 'Logan',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'df57080a-45de-450a-a220-53f95ece5829',
    givenName: 'Morgan',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'e342fc88-1589-499d-adef-f232d058b1a5',
    givenName: 'Nova',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: 'Molecular Oncologist',
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'e50f4579-727b-41b9-9c21-efb8a677e8ec',
    givenName: 'Oakley',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'e70c510f-f0f7-471e-8ca3-bd7b5ceb873b',
    givenName: 'Parker',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5;#9B51E0;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'ed84a78b-40d0-4028-8e77-7fd85239e4c1',
    givenName: 'Quinn',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: 'ZERO Paediatric Oncologist',
    avatar: 'colour:#43DED3,#27B8AF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'ef4ab1fa-cf58-4379-873c-4e153df0a3ec',
    givenName: 'Reese',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: 'Research clinical geneticist',
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'f01d52ac-eaf0-4564-99d0-f66e30804969',
    givenName: 'Sawyer',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7,#C68BFC',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'f10f8ace-5f71-4614-b2c5-9dc06c670289',
    givenName: 'Taylor',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#B5DAFF,#75B6FF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'f76a6242-84d7-45f2-9f99-b32b8dae39c2',
    givenName: 'Uma',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#AB6EE5,#9B51E0',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'fbaf1f99-ca5a-4a20-8e5c-a6bd636e7155',
    givenName: 'Val',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: 'Curator',
    avatar: 'colour:#B5DAFF,#75B6FF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'fd642313-97c6-49a9-8a66-478d0591f872',
    givenName: 'Winter',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCE174,#FAD74B',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'ff5974e6-0e18-4cf5-91fc-f968ff93feb6',
    givenName: 'Xen',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#FCB874,#F39D41',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'fffca8f9-a36d-4221-aff1-00d183de48d2',
    givenName: 'Yael',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#43DED3,#27B8AF',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
  {
    id: 'sysadmin',
    givenName: 'Zuri',
    familyName: 'Donovan',
    email: '',
    isActive: true,
    title: undefined,
    avatar: 'colour:#D9B9F7;#C68BFC;#273957',
    azureId: '',
    groups: [],
    roles: [],
    scopes: [],
    studies: [],
    sites: [],
  },
];
