import { Inject, Injectable } from '@nestjs/common';
import { Knex } from 'knex';
import { IUserWithMetadata, variantTypes } from 'Models';
import { IArchiveSample, IArchiveSamplesQuery } from 'Models/Archive/Archive.model';
import { KNEX_CONNECTION } from 'Modules/Knex/constants';
import { withClinicalVersion } from 'Utils/Query/accessControl/withClinicalVersions.util';
import { withPagination } from 'Utils/Query/Pagination.util';

@Injectable()
export class ArchiveClient {
  constructor(
    @Inject(KNEX_CONNECTION) private readonly knex: Knex,
  ) {}

  private readonly molAlterationTable = 'zcc_clinical_mol_alterations';

  private readonly meetingsTable = 'zcc_clinical_meetings';

  private readonly meetingVersionXrefTable = 'zcc_clinical_meeting_version_xref';

  public async getArchiveSamples(
    {
      page,
      limit,
      ...filters
    }: IArchiveSamplesQuery,
    user: IUserWithMetadata,
  ): Promise<IArchiveSample[]> {
    const clinicalVersions = await this.getMatchingVersions(filters);
    const query = this.knex.select('archiveSamples.*')
      .from(this.selectArchiveSamplesBase(user))
      .modify(this.withArchiveSampleFilters, filters)
      .modify(withPagination, page, limit);

    if (clinicalVersions.length) {
      query.whereIn(
        'archiveSamples.clinicalVersionId',
        clinicalVersions,
      )
        .groupBy('archiveSamples.clinicalVersionId');
    }

    return query;
  }

  public async getArchiveSamplesCount(
    filters: IArchiveSamplesQuery,
    user: IUserWithMetadata,
  ): Promise<number> {
    const clinicalVersions = await this.getMatchingVersions(filters);
    const query = this.knex.select('archiveSamples.*')
      .from(this.selectArchiveSamplesBase(user))
      .modify(this.withArchiveSampleFilters, filters)
      .as('query');

    if (clinicalVersions.length) {
      query.whereIn(
        'archiveSamples.clinicalVersionId',
        clinicalVersions,
      )
        .groupBy('archiveSamples.clinicalVersionId');
    }

    const data = await this.knex.count('* as count')
      .from(query)
      .first();

    return Number.parseInt(data.count.toString(), 10);
  }

  private selectArchiveSamplesBase(
    user: IUserWithMetadata,
  ): Knex.QueryBuilder {
    // these are the base fields we want returned to the frontend
    return this.knex
      .select({
        clinicalVersionId: 'version.id',
        analysisSetId: 'version.analysis_set_id',
        patientId: 'version.patient_id',
        cohort: 'version.cohort',
        zero2Category: 'version.zero2_category',
        zero2Subcat1: 'version.zero2_subcategory1',
        zero2Subcat2: 'version.zero2_subcategory2',
        zero2FinalDiagnosis: 'version.zero2_final_diagnosis',
        mtbDate: this.knex.raw('ANY_VALUE(meeting.date)'),
      })
      .modify(withClinicalVersion, 'from', user)
      .groupBy('version.id')
      .modify(this.withMeeting, this)
      .where('version.status', 'Done')
      .orWhere(function NAwithSlideOrRecommendation() {
        this.where('version.status', 'N/A')
          .andWhere(function withSlideOrRecommendation() {
            this.whereExists(function withRecommendation() {
              this.select('*')
                .from('zcc_clinical_recommendations')
                .whereRaw('zcc_clinical_recommendations.clinical_version_id = version.id')
                .whereNull('zcc_clinical_recommendations.deleted_at');
            })
              .orWhereExists(function withSlide() {
                this.select('*')
                  .from('zcc_clinical_slides')
                  .whereRaw('zcc_clinical_slides.clinical_version_id = version.id')
                  .whereNull('zcc_clinical_slides.deleted_at');
              });
          });
      })
      .as('archiveSamples');
  }

  // these filters apply to the fields selected in the subquery
  // generated by selectArchiveSamplesBase
  private withArchiveSampleFilters(
    qb: Knex.QueryBuilder,
    filters: IArchiveSamplesQuery,
  ): void {
    const sortColumnsMap = {

      'MTB Date': 'mtbDate',
    };
    qb
      .where(function applyFilters() {
        if (filters.search) {
          this.andWhere(function searchIds() {
            this.andWhere('archiveSamples.analysisSetId', 'like', `%${filters.search}%`)
              .orWhere('archiveSamples.patientId', 'like', `%${filters.search}%`);
          });
        }

        if (filters.cohort?.length) {
          this.whereIn('archiveSamples.cohort', filters.cohort);
        }

        if (filters.zero2Category?.length) {
          this.whereIn('archiveSamples.zero2Category', filters.zero2Category);
        }

        if (filters.zero2Subcat1?.length) {
          this.whereIn('archiveSamples.zero2Subcategory1', filters.zero2Subcat1);
        }

        if (filters.zero2Subcat2?.length) {
          this.whereIn('archiveSamples.zero2Subcategory2', filters.zero2Subcat2);
        }

        if (filters.zero2FinalDiagnosis?.length) {
          this.whereIn('archiveSamples.zero2FinalDiagnosis', filters.zero2FinalDiagnosis);
        }
      })
      .orderBy([
        ...(filters.sortColumns || []).map((col, index) => ({
          column: sortColumnsMap[col],
          order: filters.sortDirections[index],
        })),
        {
          column: 'mtbDate',
          order: 'desc',
        },
      ]);
  }

  // these filters ensure that we return only the clinical versions
  // that match all the molecular alterations
  private async getMatchingVersions(
    filters: IArchiveSamplesQuery,
  ): Promise<string[]> {
    // gather a list of sub-queries here
    const queries: Knex.QueryBuilder[] = [];

    // all the below for loops generate a query of the form
    // select clinical_version_id from mol_alteration_table where (condition)
    // There is 1 query per gene, 1 query per geneMutation, 1 query per classifier
    for (const gene of filters.geneIds || []) {
      queries.push(
        this.knex
          .select('clinical_version_id')
          .from(this.molAlterationTable)
          .where('gene_id', gene)
          .orWhere('secondary_gene_id', gene),
      );
    }

    for (const classifier of filters.classifiers || []) {
      queries.push(
        this.knex
          .select('clinical_version_id')
          .from(this.molAlterationTable)
          .where('mutation_id', classifier)
          .andWhere('mutation_type', variantTypes.find((v) => v === 'METHYLATION_CLASSIFIER')),
      );
    }

    for (const geneMutation of filters.geneMutations || []) {
      const [type, gene] = geneMutation.split(':');
      queries.push(
        this.knex
          .select('clinical_version_id')
          .from(this.molAlterationTable)
          .where(function searchGene() {
            this.where('gene', gene)
              .orWhere('secondary_gene', gene);
          })
          .andWhere('mutation_type', type),
      );
    }

    if (queries.length) {
      // This creates an intersection that returns only the clinical version id that
      // match every single subquery we created with the filters.
      // we inner join our initial query with this intersection so that
      // we only return records that match this intersection
      return this.knex.intersect(queries).pluck('clinical_version_id');
    }
    return [];
  }

  private withMeeting(
    qb: Knex.QueryBuilder,
    client: ArchiveClient,
  ): void {
    qb
      .leftJoin({ meetingXref: client.meetingVersionXrefTable }, 'version.id', 'meetingXref.clinical_version_id')
      .leftJoin({ meeting: client.meetingsTable }, 'meetingXref.meeting_id', 'meeting.id')
      .where(function meetingType() {
        this.where('meetingXref.type', 'MTB')
          .orWhereNull('meetingXref.type');
      });
  }
}
