import { IDetailedHTSResult } from '../types/HTS.types';

export const htsColumnNames: Record<
  keyof Omit<IDetailedHTSResult, 'screenId' | 'drugId'>,
  string
> = {
  biosampleId: 'HTS ID',
  drugName: 'Drug',
  compoundId: 'Drug ID',
  targets: 'Target',
  reportTargets: 'Report Targets',
  classes: 'Pathway',
  category: 'Category',
  aucPatient: 'AUC Patient',
  aucZScore: 'AUC Z-Score',
  aucMedian: 'AUC Median',
  aucZScoreSubcohort: 'AUC Z-Score Subcohort',
  aucMedianSubcohort: 'AUC Median Subcohort',
  ic50Patient: 'IC50 Patient',
  ic50Log2ZScore: 'IC50 Log2 Z-Score',
  ic50Log2Median: 'IC50 Log2 Median',
  ic50Log2: 'IC50 Log2',
  ic50Log2ZScoreSubcohort: 'IC50 Log2 Z-Score Subcohort',
  ic50Log2MedianSubcohort: 'IC50 Log2 Median Subcohort',
  ln50Patient: 'LN50 Patient',
  ln50Median: 'LN50 Median',
  lc50: 'LC50 Patient',
  lc50Log2ZScore: 'LC50 Log2 Z-Score',
  lc50Log2Median: 'LC50 Log2  Median',
  lc50Log2ZScoreSubcohort: 'LC50 Log2  Z-Score Subcohort',
  lc50Log2MedianSubcohort: 'LC50 Log2 Median Subcohort',
  lc50Log2: 'LC50 Log2',
  cmax: 'CMax',
  effectCmax: 'Effect CMax',
  css: 'CSS',
  effectCss: 'Effect CSS',
  crew: 'Crew',
  maximumEffectMtc: 'Maximum Effect MTC',
  changeRatio: 'Change from Starting point (%)',
  candidateHit: 'Candidate Hit',
  reportable: 'Reportable',
  reportingRationale: 'Reporting Rationale',
  correlation: 'Correlation to patient molecular aberration',
  hitCount: 'Hit Count',
  reportableHitCount: 'Reportable Hit Count',
  screened: 'Screened?',
};
