// Probes of interest - these probes are important for identifying the
// methylation status and thus need to be highlighted
export const poi = ['cg12434587', 'cg12981137', 'cg20931907', 'cg17779979', 'cg26217484'];

export const methyliserViewerConfig = {
  axisAlgorithm: 'rPretty',
  axisTextScaleFontFactor: 1.8,
  axisTitleFontStyle: 'bold',
  axisTitleScaleFontFactor: 1.8,
  background: '#E5E5E5',
  backgroundType: 'panel',
  boxplotColor: 'skyblue',
  boxplotWhiskersType: 'double',
  colorBy: 'probeLabel',
  colors: [
    '#1E86FC',
    '#B85CFF',
    '#0BB85E',
  ],
  dataPointSizeScaleFactor: 3,
  graphOrientation: 'horizontal',
  customizerSize: 'xxsmall',
  errorBarsThickness: '1',
  graphType: 'Boxplot',
  groupingFactors: [
    'gene',
  ],
  violinTrim: false,
  summaryType: 'iqr',
  guidesColor: '#E5E5E5',
  guidesLineType: 'solid',
  guidesShow: true,
  jitter: true,
  legendTextScaleFontFactor: 1,
  legendInside: true,
  legendPosition: 'topRight',
  objectBorderColor: '#FFFFFF00',
  panelBackgroundColor: '#FFFFFF',
  setMinX: 0,
  setMaxX: 1,
  showBoxplotIfViolin: true,
  showBoxplotOriginalData: true,
  showLegendTitle: false,
  showViolinBoxplot: true,
  smpTextRotate: '90',
  smpTextScaleFontFactor: 1.8,
  smpTitleFontStyle: 'bold',
  smpTitleScaleFontFactor: 1.8,
  stringSampleFactors: [
    'gene',
  ],
  titleAlign: 'center',
  violinBorderColor: 'skyblue',
  violinColor: 'skyblue',
  widgetsBaseColor: '#1E86FC',
  widgetsBorderColor: '#1E86FC',
  widgetsContrastColor: '#FFFFFF',
  widgetsFontColor: '#000000',
  xAxis2Show: true,
  xAxisGridMajorColor: '#E5E5E5',
  xAxisGridMinorShow: true,
  xAxisTitle: 'Beta value',
} as const;
