export * from './Sample/Sample.client';
export * from './Slide/Slide.client';
export * from './MolecularAlterations/MolecularAlterations.client';
export * from './Drug/Drug.client';
export * from './Therapy/Therapy.client';
export * from './Recommendation/Recommendation.client';
export * from './Evidence/Evidence.client';
export * from './Comment/Comment.client';
export * from './Meetings/Meetings.client';
