import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("zcc_clinical_hts_drug_screening").del();

  // Inserts seed entries
  await knex("zcc_clinical_hts_drug_screening").insert([
    {
      hts_drug_id: "1",
      drug_id: "1",
      dose_pk: "Test dose pk 1",
      dose_schedule: "Test dose schedule 1",
      dose_paediatric: "Test dose paediatric 1",
      dose_tolerance: "Test dose tolerance 1",
      cmax_ng_ml: 1.0,
      cmax_uM: 1.0,
      css_ng_ml: 1.0,
      css_uM: 1.0,
      css_peak: "Test css peak 1",
      max_response: "Test max response 1",
      tumour_type: "Test tumour type 1",
      crpc_uM: 1.0,
      crpc_nM: 1.0,
      paed_cancer_trial: "Test paediatric cancer trial 1",
      include_reason: "Test include reason 1",
      notes: "Test notes 1",
      blood_brain_barrier: "Test blood brain barrier 1",
      fda_approved: true,
      tga_approved: true,
    },
    {
      hts_drug_id: "2",
      drug_id: "2",
      dose_pk: "Test dose pk 2",
      dose_schedule: "Test dose schedule 2",
      dose_paediatric: "Test dose paediatric 2",
      dose_tolerance: "Test dose tolerance 2",
      cmax_ng_ml: 2.0,
      cmax_uM: 2.0,
      css_ng_ml: 2.0,
      css_uM: 2.0,
      css_peak: "Test css peak 2",
      max_response: "Test max response 2",
      tumour_type: "Test tumour type 2",
      crpc_uM: 2.0,
      crpc_nM: 2.0,
      paed_cancer_trial: "Test paediatric cancer trial 2",
      include_reason: "Test include reason 2",
      notes: "Test notes 2",
      blood_brain_barrier: "Test blood brain barrier 2",
      fda_approved: false,
      tga_approved: false,
    },
    {
      hts_drug_id: "3",
      drug_id: "3",
      dose_pk: "Test dose pk 3",
      dose_schedule: "Test dose schedule 3",
      dose_paediatric: "Test dose paediatric 3",
      dose_tolerance: "Test dose tolerance 3",
      cmax_ng_ml: 3.0,
      cmax_uM: 3.0,
      css_ng_ml: 3.0,
      css_uM: 3.0,
      css_peak: "Test css peak 3",
      max_response: "Test max response 3",
      tumour_type: "Test tumour type 3",
      crpc_uM: 3.0,
      crpc_nM: 3.0,
      paed_cancer_trial: "Test paediatric cancer trial 3",
      include_reason: "Test include reason 3",
      notes: "Test notes 3",
      blood_brain_barrier: "Test blood brain barrier 3",
      fda_approved: true,
      tga_approved: true,
    },
  ]);
};
