import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('zcc_clinical_mol_alterations').del();

  // Inserts seed entries
  await knex('zcc_clinical_mol_alterations').insert([
    {
      id: '1',
      mutation_id: '1',
      mutation_type: 'SNV',
      gene: 'RARA',
      gene_id: '13794',
      pathway: 'RTK Pathway',
      pathway_id: '1',
      alteration: 'RARA pathogenic variant associated with HTZ deletion',
      curation_reportable: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_targetable: true,
      curation_targetable: false,
      high_relapse_risk: false,
      curation_comment: 'mol alteration curation comment 1',
      additional_data: JSON.stringify({
        consequence: 'missense_variant',
        vaf: '2',
        variantCN: '2.98',
        cnLoh: '34.7',
        pathogenicity: '23.4',
        subclonalLikelihood: '12',
      }),
    },
    {
      id: '2',
      mutation_id: '2',
      mutation_type: 'CNV',
      gene: 'TP53',
      gene_id: '60',
      pathway: 'TP53 Signaling Pathway',
      pathway_id: '2',
      alteration: 'High RNA expression FC 2.81, Z-score 1.258',
      curation_reportable: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_targetable: true,
      high_relapse_risk: true,
      curation_comment: 'mol alteration curation comment 2',
      additional_data: JSON.stringify({
        copyNoType: 'DEL',
        copyNoMin: '0.961',
        copyNoMax: '1.972',
        segmental: true,
      }),
    },
    {
      id: '3',
      mutation_id: '3',
      mutation_type: 'SV',
      gene: 'SMARCE1',
      gene_id: '42',
      pathway: 'SWI/SNF Complex',
      pathway_id: '3',
      alteration: 'High RNA expression FC 4.8, Z-Score 1.6',
      curation_reportable: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      curation_targetable: true,
      clinical_targetable: false,
      high_relapse_risk: true,
      curation_comment: 'mol alteration curation comment 3',
      additional_data: JSON.stringify({
        startGene: 'EWSR1',
        endGene: 'FLI1',
      }),
    },
    {
      id: '4',
      mutation_id: '4',
      mutation_type: 'GERMLINE_SNV',
      gene: 'PHOX1A',
      gene_id: '999998',
      pathway: 'Test Pathway 1',
      pathway_id: '4',
      alteration: 'High RNA expression FC 6.4, Z-Score 1.9',
      curation_reportable: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      curation_targetable: false,
      clinical_targetable: false,
      high_relapse_risk: false,
      curation_comment: 'mol alteration curation comment 4',
      additional_data: JSON.stringify({
        phenotypeMatch: 'Met269Arg',
        consequence: 'missense_variant',
      }),
    },
    {
      id: '5',
      mutation_id: '5',
      mutation_type: 'GERMLINE_CNV',
      gene: 'PHOX1B',
      gene_id: '999999',
      pathway: 'Test Pathway 2',
      pathway_id: '5',
      alteration: 'Hemizgous pathogenic variant',
      curation_reportable: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      curation_targetable: false,
      clinical_targetable: false,
      high_relapse_risk: true,
      curation_comment: 'mol alteration curation comment 5',
      additional_data: JSON.stringify({
        copyNoType: 'DEL',
        copyNoMin: '0.961',
        copyNoMax: '1.972',
        segmental: true,
      }),
    },
    {
      id: '6',
      mutation_id: '6',
      mutation_type: 'RNA_SEQ',
      gene: 'CDK9',
      gene_id: '14',
      pathway: 'Test Pathway 3',
      pathway_id: '6',
      alteration: 'Test alteration 1',
      curation_reportable: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_targetable: true,
      high_relapse_risk: true,
      curation_comment: 'mol alteration curation comment 6',
      additional_data: JSON.stringify({
        foldChange: '9.8231',
        zScore: '3.956',
        // This file id exist in dev file_tracker db
        tpmGraphFileId: '00fb4eb3-79ca-4988-b063-706f10277d54',
      }),
    },
    {
      id: '54fa0cde-60a7-11ed-8395-0b0701efb0a1',
      mutation_id: 'OS_HG',
      mutation_type: 'METHYLATION_CLASSIFIER',
      gene: '',
      pathway: '',
      pathway_id: '',
      alteration: 'MNP Brain Classifier v.12.5',
      curation_reportable: '1',
      curation_targetable: true,
      clinical_reportable: 'Response',
      clinical_targetable: false,
      additional_data: {
        classifier: 'MNP Brain Classifier v.12.5',
        methClass: 'Ependymoma, posterior fossa group A',
        score: 0.9,
        interpretation: 'match',
      },
      frequency: 1.2,
      high_relapse_risk: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_notes: 'Some note',
      clinical_alteration: '',
      description: 'Ependymoma, posterior fossa group A (0.90)',
    },
    {
      id: '64fa0cde-60a7-11ed-8395-0b0701efb0a1',
      mutation_id: 'OS_HG',
      mutation_type: 'METHYLATION_CLASSIFIER',
      gene: '',
      pathway: '',
      pathway_id: '',
      alteration: 'MNP medulloblastoma v.1',
      curation_reportable: '1',
      curation_targetable: true,
      clinical_reportable: 'Response',
      clinical_targetable: false,
      additional_data: {
        classifier: 'MNP medulloblastoma v.1',
        methClass: 'Classifier group 3/4',
        score: 0.88,
        interpretation: 'match',
      },
      frequency: 1.2,
      high_relapse_risk: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_notes: 'Some note',
      clinical_alteration: '',
      description: 'Classifier group 3/4 (0.88)',
    },
    {
      id: '74e31c79-60a7-11ed-8395-0b0701efb0a1',
      mutation_id: 'mgmt',
      mutation_type: 'METHYLATION_MGMT',
      gene: '',
      pathway: '',
      pathway_id: '',
      alteration: 'MGMT',
      curation_reportable: '1',
      curation_targetable: true,
      clinical_reportable: 'Treatment',
      clinical_targetable: true,
      additional_data: {
        status: 'Methylated',
        gene: 'MGMT',
      },
      frequency: 1.3,
      high_relapse_risk: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_notes: '',
      clinical_alteration: '',
      description: 'Unmethylated',
    },
    {
      id: '44fa0cde-60a7-11ed-8395-0b0701efb0a1',
      mutation_id: 'OS_HG',
      mutation_type: 'METHYLATION_CLASSIFIER',
      gene: '',
      pathway: '',
      pathway_id: '',
      alteration: 'MNP Brain Classifier v.11b',
      curation_reportable: '1',
      curation_targetable: true,
      clinical_reportable: 'Response',
      clinical_targetable: false,
      additional_data: {
        classifier: 'MNP Brain Classifier v.11b',
        methClass: 'Ependymoma, posterior fossa group A',
        score: 0.92,
        interpretation: 'match',
      },
      frequency: 1.2,
      high_relapse_risk: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_notes: 'Some note',
      clinical_alteration: '',
      description: 'Ependymoma, posterior fossa group A (0.92)',
    },
    {
      id: '10',
      mutation_id: '10',
      mutation_type: 'MUTATIONAL_SIG',
      alteration: 'Signature 6',
      curation_reportable: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_targetable: true,
      high_relapse_risk: true,
      curation_comment: 'mol alteration curation comment 10',
      description: '(56.5%) - Defective DNA mismatch repair',
      clinical_reportable: 'Diagnostic',
    },
    {
      id: '7',
      mutation_id: '7',
      mutation_type: 'CYTOGENETICS_ARM',
      alteration: '1q23.1;1q23.2;1q23.3;1q24.1',
      curation_reportable: true,
      sample_id: 'LKCGP-P009102-326840-01-04-01-D1',
      patient_id: 'P009102',
      clinical_version_id: '1',
      clinical_targetable: true,
      high_relapse_risk: true,
      curation_comment: 'mol alteration curation comment 7',
      description: 'Copy Gain - CN: 3.99',
      clinical_reportable: 'Diagnostic',
      additional_data: JSON.stringify({
        chromosome: '1',
        arm: 'q',
        type: 'Copy Gain',
        copyNumber: '4.99765',
      }),
    },
  ]);
}
